### ISSUE TITLE
Alternative Install instructions for Package Control

### ISSUE THREAD

**Issue by yougotwill** [mauroreisvieira/github-sublime-theme#1]
Amazed someone ported this so quickly! Thanks so much :)

Here is an alternative way to install this package via Package Control. This allows updating and management via Package Control.

**Package Control:**

1. Open `Command Palette` using menu item `Tools → Command Palette` or <kbd>CMD/CTRL</kbd> + <kbd>SHIFT</kbd> +<kbd>P</kbd>.
2. Choose `Package Control: Add Repository`.
3. Enter `https://github.com/mauroreisvieira/github-sublime-theme` into the bottom panel and press <kbd>ENTER</kbd>.
4. Open Command Palette using menu item Tools → Command Palette or CMD/CTRL + SHIFT +P.
5. Choose Package Control: Install Package.
6. Type `github-sublime-theme` and press <kbd>ENTER</kbd>.

**Comment by mauroreisvieira** [comment]
Hi @yougotwill thanks for like that.

The issue to this way, it's the folder naming. 
Since I add some custom icons, I need a different name folder.

**Comment by yougotwill** [comment]
Ah okay. I'll close the issue then 👍
