### ISSUE TITLE
No file icons are shown in the sidebar (ST3)

### ISSUE THREAD

**Issue by Drarok** [mauroreisvieira/github-sublime-theme#10]
**Describe the bug**
According to the screenshots, I should see nice relevant icons for common file types, but when I install the theme I see none.

**To Reproduce**
1. Use Sublime Text 3
2. Install and select the theme and color scheme
3. View the sidebar

**Expected behavior**
Icons should be shown in the sidebar.

**Screenshots**
![Screenshot 2021-04-28 at 13 18 26](https://user-images.githubusercontent.com/55830/116402408-4f709780-a824-11eb-95a7-a4253f856e26.png)

**Comment by Drarok** [comment]
Oh! I restarted in order to set up a different plugin, and now the icons are shown! Maybe it's just a bug immediately after install?

![Screenshot 2021-04-28 at 13 21 43](https://user-images.githubusercontent.com/55830/116402815-c148e100-a824-11eb-8bb9-d167364f552e.png)

**Comment by Xosmond** [comment]
I experiencing the same problem, still remain after restarted sublime.

**Comment by phyothiha** [comment]
@Xosmond Works like a charm!!!
