### ISSUE TITLE
Matched occurrences of selection are invisible

### ISSUE THREAD

**Issue by maxime-pigeon** [mauroreisvieira/github-sublime-theme#16]
**Describe the bug**
Matching occurrences of the currently selected text are usually highlighted by default, but they aren't when using the GitHub theme (although, interestingly, they are when using the Legacy schemes).

**To Reproduce**
1. Enable Github theme.
2. Make sure "match_selection" is true in your preferences.
3. Select any text that occurs more than once in the buffer.

**Expected behavior**
Matched occurrences should be highlighted.

BTW, thank you for your good work on this theme!

**Comment by mauroreisvieira** [comment]
Thanks, @maxime-pigeon for your report and for using GitHub Theme, I will fix that issue ASAP. 

Thanks 💪
