### ISSUE TITLE
Dirty(Modified) files can't be distinguished from saved files in the side bar "OPEN FILES" region

### ISSUE THREAD

**Issue by absop** [mauroreisvieira/github-sublime-theme#17]
**Expected behavior**
![image](https://user-images.githubusercontent.com/32818900/149330188-c67a1ba9-8bce-4726-9241-21779954f607.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/32818900/149330304-25bbb4c8-6dd0-4743-8267-c6f90cc3d494.png)

**Comment by mauroreisvieira** [comment]
Thanks, @absop for your report, I will solve that ASAP.

**Comment by absop** [comment]
Thanks, for your great work!

> Thanks, @absop for your report, I will solve that ASAP.

**Comment by absop** [comment]
Hi, this issue was indeed fixed. However, every time Sublime Text starts up (or the theme is loaded), Sublime Text's console prints out some error information about the theme.
```text
Errors parsing theme:
  the variable "sidebar_button_hover_opacity" is not defined in Packages\GitHub Theme\GitHub Light.sublime-theme:1179:31
```

**Comment by mauroreisvieira** [comment]
Thanks @absop for report, I will fix that.
