### ISSUE TITLE
Strings are wrong color

### ISSUE THREAD

**Issue by trobjo** [mauroreisvieira/github-sublime-theme#2]
Hello!

Nice theme. Most of the Sublime themes out there try to do too much, which is more confusing than helpful. Therefore, I was glad when I found your theme trying to mimic Github's theme.

Anyway, your color for strings is wrong, it should be hsl(212.2, 94.1%, 19.8%)

![Screenshot_2020-06-09_100524](https://user-images.githubusercontent.com/26080212/84122502-cfd5b080-aa38-11ea-9503-971ac4559573.png)

**Comment by mauroreisvieira** [comment]
Hi @trobjo, thanks for you report, I will fix that, and also thank you so much for using and liking this theme.
