### ISSUE TITLE
Better links highlighting 

### ISSUE THREAD

**Issue by artofhuman** [mauroreisvieira/github-sublime-theme#20]
**Describe the bug**
Links are not readable in current color. 

**Screenshots**
LSP package
<img width="1158" alt="image" src="https://github.com/user-attachments/assets/c6be4ce9-4d2f-476c-bb33-77728afe5f96">

Menu
<img width="704" alt="image" src="https://github.com/user-attachments/assets/cc5b805a-a2b8-4c41-962e-91defea9eb3f">

**Comment by mauroreisvieira** [comment]
Hey @artofhuman, thanks for the report, could you please provide more details? 
Specifically, what theme and color scheme are you using?

**Comment by artofhuman** [comment]
UI Theme - Adaptive
Color Scheme - Github Dimmed

**Comment by mauroreisvieira** [comment]
The theme is the `Github Adaptive` or the `Adaptive` (from ST)?

**Comment by artofhuman** [comment]
Adaptive from ST

**Comment by mauroreisvieira** [comment]
In this case, it's not an issue with the GitHub Theme. The link colors are controlled by the theme, not by the color scheme.

**Comment by artofhuman** [comment]
Same with GitHub adaptive UI theme (maybe a bit better, but still unreadable) 

<img width="556" alt="image" src="https://github.com/user-attachments/assets/9a73084d-c684-465f-8ad6-882b60c4bd17">

**Comment by artofhuman** [comment]
Nord with Gihub Adaptive

<img width="562" alt="image" src="https://github.com/user-attachments/assets/cf8b50aa-19b3-4311-8161-69189e30e2e3">
