### ISSUE TITLE
Black Tabs bug in github light theme after update

### ISSUE THREAD

**Issue by richardnassour** [mauroreisvieira/github-sublime-theme#5]
![sublime_text_MmU7Rdbnhb](https://user-images.githubusercontent.com/33163707/96300369-172f0780-0ffe-11eb-9fc5-97d4c6ef6b89.png)

**Comment by mauroreisvieira** [comment]
Hi @richardnassour thanks for you report.

I don't have that issue, can you send what version of ST do you have?
