### ISSUE TITLE
Remove custom code for disabling tab navigation

### ISSUE THREAD

**Issue by iPyGuy** [mauroreisvieira/github-sublime-theme#6]
This theme suggests adding `"show_tab_navigation": "false",` to your settings but it is not necessary as SublimeText already natively supports enabling/disabling the tab navigation buttons using the setting `"enable_tab_scrolling": false,` instead.

**Comment by mauroreisvieira** [comment]
Hi @iPyGuy  thanks for your report. 

It's fixed in new version.
