### ISSUE TITLE
Split the theme into separate files

### ISSUE THREAD

**Issue by iPyGuy** [mauroreisvieira/github-sublime-theme#7]
Currently there are 2 color schemes (light & dark) but only 1 theme.
So they way it works right now is by automatically setting the theme to light when you're using the light scheme and setting the theme to dark when you're using the dark scheme.

However, I'd rather have the option to use any combination of light and dark. Sometimes I like using a light theme with a dark scheme or vice versa.
Splitting the theme into 2 separate files - one light and one dark - would make that possible.

**Comment by mauroreisvieira** [comment]
Hi @iPyGuy now Github Theme it's adaptive, so the Theme will responde to the Scheme color selected.
But the point that you refering about combination with Dark Theme with Light Scheme it's a good point. 

Thanks for your feedback.
