### ISSUE TITLE
Some icons rendered abnormally

### ISSUE THREAD

**Issue by absop** [mauroreisvieira/github-sublime-theme#8]
The theme render icons for some files abnormally, such as `README`, `.gitignore`, and git Untracked files etc.

![image](https://user-images.githubusercontent.com/32818900/115224697-c54b7380-a13f-11eb-8040-02b1be885c31.png)

**Comment by mauroreisvieira** [comment]
Hey, @absop thanks for the report. I will fix that ASAP.

**Comment by absop** [comment]
Thanks for replying and your great job, this theme is pretty nice. 

The icons for `.gitignore` and `README.md` filse is not that mean, it is actually for `+` of git diff.

Here is the display of same files under other theme. 

![image](https://user-images.githubusercontent.com/32818900/115336054-017ae480-a1d1-11eb-9400-6916ed9dd6fc.png)

**Comment by mauroreisvieira** [comment]
Hey @absop I understand, because on Github Theme I use some letters (M, S, U) instead of a simple dot on plus. 

Can you tell me what version of Sublime you use and what is your machine (Mac, Window, or Linux)?

p.s: I'm working on the Dimmend version, so I will do everything in the same release.

**Comment by absop** [comment]
Sublime Text 4102, Windows 10
| |
zlang0
|
|
***@***.***
|
签名由网易邮箱大师定制
On 4/20/2021 17:44，Mauro Reis ***@***.***> wrote：

Hey @absop I understand, because on Github Theme I use some letters (M, S, U) instead of a simple dot on plus.

Can you tell me what version of Sublime you use and what is your machine (Mac, Window, or Linux)?

p.s: I'm working on the Dimmend version, so I will do everything in the same release.

**Comment by absop** [comment]
Hi, Thanks for you to keep going to work on this theme. It has been updated on my machine know, but the issue still there while I select the entry of `Github theme`, and there is a new issue, that is the icon of folders has been changed, but only occurs in the `Github theme` entry.
 
![image](https://user-images.githubusercontent.com/32818900/115801067-72f3a680-a40e-11eb-92bd-96ad99453594.png)

**Comment by absop** [comment]
And if I make use of the combination of the **Github theme** `Theme` and some another `Color Scheme`, the icon will be shown as below.

![image](https://user-images.githubusercontent.com/32818900/115801333-13e26180-a40f-11eb-9698-92c500ba6be3.png)

**Comment by absop** [comment]
And I found two issue of the **Dark** & **Dimmed** variant.
- The first one is about the tab bar, the main color of the tab bar does not match the color of the tabs.
- The second one is about the font displayed in status bar, which is a little blurry.


![image](https://user-images.githubusercontent.com/32818900/115801877-607a6c80-a410-11eb-97c8-de3a6d1e8f43.png)
![image](https://user-images.githubusercontent.com/32818900/115801897-696b3e00-a410-11eb-9a9e-64c6f08a0f9a.png)

**Comment by mauroreisvieira** [comment]
Hi @absop GitHub Theme not exists, now we have:

- GitHub Light 
- GitHub Dark
- GitHub Dimmed

ST save GitHub Theme in your local machine, but in reality, it's was deleted. 

---

> And I found two issue of the **Dark** & **Dimmed** variant.
> 
> * The first one is about the tab bar, the main color of the tab bar does not match the color of the tabs.
> * The second one is about the font displayed in status bar, which is a little blurry.
> 
> ![image](https://user-images.githubusercontent.com/32818900/115801877-607a6c80-a410-11eb-97c8-de3a6d1e8f43.png)
> ![image](https://user-images.githubusercontent.com/32818900/115801897-696b3e00-a410-11eb-9a9e-64c6f08a0f9a.png)

About that I will check, thanks for the report.

**Comment by absop** [comment]
> Hi @absop GitHub Theme not exists, now we have:
> 
> * GitHub Light
> * GitHub Dark
> * GitHub Dimmed
> 
> ST save GitHub Theme in your local machine, but in reality, it's was deleted.
> 
> > And I found two issue of the **Dark** & **Dimmed** variant.
> > 
> > * The first one is about the tab bar, the main color of the tab bar does not match the color of the tabs.
> > * The second one is about the font displayed in status bar, which is a little blurry.
> > 
> > ![image](https://user-images.githubusercontent.com/32818900/115801877-607a6c80-a410-11eb-97c8-de3a6d1e8f43.png)
> > ![image](https://user-images.githubusercontent.com/32818900/115801897-696b3e00-a410-11eb-9a9e-64c6f08a0f9a.png)
> 
> About that I will check, thanks for the report.

The `Github Theme.sublime-theme` file still included by the package.
[Github Theme](https://github.com/mauroreisvieira/github-sublime-theme/blob/main/GitHub-Theme.sublime-theme)

**Comment by mauroreisvieira** [comment]
WOW, it was an error, which must have occurred during the merge.

But it will be eliminated.

Regarding the Tabs the problem is the fact that the Theme extender of the Adaptive Theme native to ST.

I will resolve this ASAP

**Comment by mauroreisvieira** [comment]
Hey, @absop can you please tell me if, the issues were solved?

**Comment by absop** [comment]
Yes, it's solved. It looks much better than before, it's a  significant improvement. 
There is just a little problem, that is, the dark series themes input box seems a little too bright in contrast to the surrounding colors, I think we can make them a little darker.

![image](https://user-images.githubusercontent.com/32818900/116121451-31efe080-a6f3-11eb-85e0-6f0789580a65.png)
![image](https://user-images.githubusercontent.com/32818900/116121268-0967e680-a6f3-11eb-895b-18170cc731ec.png)

**Comment by mauroreisvieira** [comment]
Hey, thanks for your feedback.

That is not possible to fix, because the color of the text inside the input comes from the scheme, so is not possible to customize it. 

I can change the Input background, but with **Light Schemes** will be not possible to read what is written inside.

**Comment by absop** [comment]
Another problem is, under the Light theme, when the console line input box loses focus, it's color goes gray.

![image](https://user-images.githubusercontent.com/32818900/116123453-9613a400-a6f5-11eb-880f-fae3475c186c.png)
![image](https://user-images.githubusercontent.com/32818900/116123426-901dc300-a6f5-11eb-88c2-701ab40a4f3d.png)

**Comment by absop** [comment]
> Hey, thanks for your feedback.
> 
> That is not possible to fix, because the color of the text inside the input comes from the scheme, so is not possible to customize it.
> 
> I can change the Input background, but with **Light Schemes** will be not possible to read what is written inside.

That's okay. I got it.

**Comment by absop** [comment]
I actually liked the theme that automatically adapts to the Color Scheme (The privious `Github Theme`). I think we can keep it, by making it complete and adding some Settings for it to give users some room to personalize it (such as adjusting the height of tab bar). In addition, the Light, Dimmed, and Dark themes can inherit the adaptive `GitHub Theme` directly by setting the variables in the `GitHub Theme` to a fixed value. This makes it easier to maintain these themes.

**Comment by mauroreisvieira** [comment]
In fact, I created the [Meetio Theme](https://github.com/meetio-theme/sublime-meetio-theme) which is fully adaptable to the scheme color, so you can install and do a lot of overrides to default variables.

But the idea of **GitHub Theme** is no longer an adaptable one, but a "copy" adapted to Sublime Text from [GitHub's VS Code themes](https://github.com/primer/github-vscode-theme).

So, for now, I don't have a plan to put GitHub Theme adaptive again.

**Comment by Drarok** [comment]
I'm still on the release version of ST3, and the icons are messed up for me too. Can we get the fix back-ported to the ST3 releases please?

**Comment by mauroreisvieira** [comment]
Hey @Drarok, I will fix that on ST3.
